### ISSUE TITLE
backend api 에서 bcrypt를 대체한 프로젝트를 올려주실수는 없을까요?

### ISSUE THREAD

**Issue by julio-kim** [ZeroCho/sleact#1]
안녕하세요
인프런에서 강사님 강의를 수강하고 있는데요.

M1 mac을 사용하고 있는데 bcrypt 문제로 강의진행을 못하고 있습니다.
bcrypt를 대신 다른 라이브러리로 대체해서 back을 다시 올려주실 수 있을까요?

**Comment by ZeroCho** [comment]
안녕하세요.

m1이라고 bcrypt를 못 쓸 이유가 없어 보입니다.
https://github.com/kelektiv/node.bcrypt.js/issues/868#issuecomment-875374534
비슷한 이슈면 이걸로 해결해보세요.

감사합니다.
조현영 드림.

2021년 11월 13일 (토) 오후 5:38, Julio Kim ***@***.***>님이 작성:

**Comment by julio-kim** [comment]
주말인데 빠른 회신 감사합니다~:)

우선, 연결해주신 이슈를 확인하고 동일하게 진행을 해보았는데요.
해당 게시글 바로 밑에 추가 답변을 달으신 분과 동일한 이슈로 설치가 되지 않았습니다.
그런데, 잘 살펴보니 문제가 해결이 되지 않으신 분의 Node 버전은 16버전으로 저하고 동일한데,
해결이 되었다는 분의 버전은 14버전이더라구요.

혹시나해서, 버전을 내려보니 해결이 되었습니다.
이 문제가 단순히 버전만 내려서 해결되는 문제였는지,
아니면 아래의 명령까지 실행이 된 상태에서 14버전으로 내려서 해결된 것인지는
이미 실행을 해버린터라 알수가 없네요ㅜㅜ

하여튼, 답변 감사드립니다~:)
